# Generated by Django 5.2.17 on 2026-09-05 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(blank=True, default='Hospital', max_length=50),
        ),
    ]
